version:     "0007--11-Feb-2022"
copyright:   "2022"
author:      "Ahsan Najmy"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/ahsannajmy/os221"
myloglink:   "mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]

theme: jekyll-theme-cayman